[project]
name = "summer-modules-prefect"
dynamic = ["version"]
description = "Prefect helper utilities for summer-modules"
requires-python = ">=3.11"
dependencies = [
    "prefect>=3.4.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "../../VERSION"

[tool.hatch.build.targets.wheel]
packages = ["src/summer_modules_prefect"]
