deepseek_apikey = "sk-xxx"
github_token = "github_pat_xxx"
otx_api_key = "xxxxxxxx"

[image_host]
[image_host.gitlab]
gitlab_token = "xxx"
project_id = "xxxx"
branch = "main"
repo_path = "xxxx"
gitlab_base_url = "https://gitlab.com"
gitlab_repo_image_base_path = "xxx/xxx"

[database]
[database.hbase]
host = "localhost"
thrift_port= 8080
username = "hbase"
password = "hbase"

[database.postgres]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
database = "summer_modules"


[ssh]
hostname = "localhost"
username = "root"
password = "root"
port = 22

[hbase_ssh_output_test]
src_filepath = ""
out_json_filepath = ""

[bot]
[bot.wxwork]
webhook = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx"