[project]
name = "summer-modules-security"
dynamic = ["version"]
description = "Security tooling and threat intelligence helpers for summer-modules"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "beautifulsoup4>=4.12.3",
    "openpyxl>=3.1.5",
    "summer-modules-core>=1.1.0",
    "summer-modules-ai>=1.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "../../VERSION"

[tool.hatch.build.targets.wheel]
packages = ["src/summer_modules_security"]
