[project]
name = "summer-modules-charts"
dynamic = ["version"]
description = "Chart utilities for summer-modules"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "summer-modules-core>=1.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "../../VERSION"

[tool.hatch.build.targets.wheel]
packages = ["src/summer_modules_charts"]
