name: Release packages

on:
  push:
    tags:
      - "v*"

jobs:
  test-and-publish:
    name: Test and publish to PyPI
    runs-on: ubuntu-latest
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      UV_LINK_MODE: copy
      UV_PYTHON: "3.12"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.8.22"

      - name: Ensure Python 3.13 available to uv
        run: uv python install 3.12

      - name: Sync dependencies
        run: uv sync --dev

      - name: Ensure test tools
        run: uv pip install pytest toml

      - name: Run tests
        run: uv run pytest packages/summer_modules_*/tests

      - name: Publish workspace packages
        run: |
          set -euo pipefail

          packages=(
            summer-modules-core
            summer-modules-ai
            summer-modules-bot
            summer-modules-markdown
            summer-modules-charts
            summer-modules-database
            summer-modules-excel
            summer-modules-prefect
            summer-modules-security
            summer-modules-ssh
          )

          for pkg in "${packages[@]}"; do
            echo "::group::Publishing ${pkg}"
            uv build --package "${pkg}"
            uv publish --package "${pkg}" --yes
            echo "::endgroup::"
          done

          echo "::group::Publishing summer-modules (aggregator)"
          uv build
          uv publish --yes
          echo "::endgroup::"
